name: Authenticator
main: com.huskydreaming.authenticator.Authenticator
version: 1.0.0-BETA
api-version: 1.18
author: HuskyDreaming

commands:
  authenticator:
    aliases: [auth, authentication]
    description: Authentication command.