name: Authenticator
main: com.huskydreaming.authenticator.Authenticator
version: 0.1.2-ALPHA
api-version: 1.18
author: HuskyDreaming

commands:
  authenticator:
    aliases: [auth, authentication]
    description: Authentication command.